[geometry][index]: boost::swap() for unsigned ints changed to std::swap() because of error C2872: 'swap' : ambiguous symbol in msvc 8 and 9.
git-svn-id: http://svn.boost.org/svn/boost/trunk@84821 b8fc166d-592f-0410-95f2-cb63ce0dd405